package ec.edu.espe.repasoprueba.view;

import ec.edu.espe.repasoprueba.controller.PaintingController;
import ec.edu.espe.repasoprueba.model.Painting;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmView extends javax.swing.JFrame {

    private PaintingController controller;

    /**
     * Creates new form FrmView
     */
    public FrmView() {
        controller = new PaintingController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPainting = new javax.swing.JTable();
        txtColors = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        jLabel1.setText("Galery");

        jLabel2.setText("Name:");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel3.setText("Base Price ($):");

        jLabel4.setText("Colors:");

        btnCreate.setText("Create New");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Changes");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Clear Form");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("Inventory:");

        tabPainting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Colors", "Price ", "Price IVA"
            }
        ));
        jScrollPane1.setViewportView(tabPainting);

        jLabel6.setText("id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFind))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColors, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabPainting.getModel();

        if (tabPainting.isEditing()) {
            tabPainting.getCellEditor().stopCellEditing();
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No data to update.");
            return;
        }

        int successCount = 0;
        int errorCount = 0;

        // Recorremos la tabla visual fila por fila
        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                // Obtenemos el ID tal cual está en la tabla
                String id = String.valueOf(model.getValueAt(i, 0));
                String name = String.valueOf(model.getValueAt(i, 1));
                String colorsText = String.valueOf(model.getValueAt(i, 2));

                // Convertimos el precio. Si falla, avisamos.
                double price = Double.parseDouble(model.getValueAt(i, 3).toString());

                // Convertimos colores
                List<String> colorsList = parseColors(colorsText);

                // Llamamos al controller (que ahora sí valida si existe el ID)
                boolean actualizado = controller.updatePainting(id, name, price, colorsList);

                if (actualizado) {
                    successCount++;
                } else {
                    errorCount++;
                    System.out.println("No se pudo actualizar ID: " + id + " (Probablemente no existe en MongoDB)");
                }

            } catch (Exception e) {
                System.out.println("Error en fila " + i + ": " + e.getMessage());
            }
        }
        
        if (successCount > 0) {
            JOptionPane.showMessageDialog(this, successCount + " paintings were updated");
            loadTableData(null); // Recargamos para ver el IVA calculado desde la BD
        } else if (errorCount > 0) {
            JOptionPane.showMessageDialog(this, "Error, ID didn't find");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String idToSearch = txtId.getText();

        if (idToSearch.isEmpty()) {
            // Si está vacío, recargamos toda la tabla
            loadTableData(null);
        } else {
            // 2. Buscamos usando el Id
            Painting foundPainting = controller.findPaintingById(idToSearch);

            if (foundPainting != null) {
                // 3. Mostramos solo ese resultado en la lista
                List<Painting> results = new ArrayList<>();
                results.add(foundPainting);
                loadTableData(results);
            } else {
                JOptionPane.showMessageDialog(this, "Painting with ID " + idToSearch + " not found.");
                loadTableData(null); // Limpiamos si no encuentra
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        loadTableData(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            String id = txtId.getText();
            String name = txtName.getText();
            double price = Double.parseDouble(txtBasePrice.getText());
            List<String> colors = parseColors(txtColors.getText());

            if (controller.createPainting(id, name, price, colors)) {
                JOptionPane.showMessageDialog(this, "Painting Save");
                clearForm();
                loadTableData(null);
            } else {
                JOptionPane.showMessageDialog(this, "Error to save");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Prices's format is wrong");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tabPainting.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
            return;
        }

        // Detener edición por si acaso
        if (tabPainting.isEditing()) {
            tabPainting.getCellEditor().stopCellEditing();
        }

        // Obtener ID de la columna 0
        String idToDelete = tabPainting.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "¿Are you sure to want to delete the ID: " + idToDelete + "?");
        if (confirm == JOptionPane.YES_OPTION) {

            boolean deleted = controller.deletePainting(idToDelete);

            if (deleted) {
                JOptionPane.showMessageDialog(this, "Eliminado correctamente de MongoDB.");
                loadTableData(null);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar. El ID no se encontró en la base de datos.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void loadTableData(List<Painting> dataList) {
        DefaultTableModel model = (DefaultTableModel) tabPainting.getModel();
        model.setRowCount(0); // Limpiar tabla

        // Si dataList es null, traemos todo del controlador
        List<Painting> list = (dataList == null) ? controller.getAllPaintings() : dataList;

        for (Painting painting : list) {
            Object[] row = {
                String.valueOf(painting.getId()),
                painting.getName(),
                String.join(", ", painting.getColors()), // Convertimos la lista de colores a texto para que se vea y NO SE PIERDA
                painting.getPrice(),
                painting.getPriceWithIva()
            };
            model.addRow(row);
        }
    }

    // Convierte texto "Rojo, Azul" -> List["Rojo", "Azul"]
    private List<String> parseColors(String text) {
        if (text == null || text.trim().isEmpty()) {
            return new ArrayList<>();
        }

        // Split por coma, y trim a cada elemento para quitar espacios
        return Arrays.stream(text.split(","))
                .map(String::trim)
                .collect(Collectors.toList());
    }

    private void clearForm() {
        txtId.setText("");
        txtName.setText("");
        txtBasePrice.setText("");
        txtColors.setText("");
        tabPainting.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPainting;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtColors;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
